#!/bin/sh
set -eu

root=${0%/*}
app_storage=osu-cpp.j4niwzis
export XDG_DATA_HOME="$HOME/.local/share/$app_storage"
export XDG_CONFIG_HOME="$HOME/.config/$app_storage"
export XDG_CACHE_HOME="$HOME/.cache/$app_storage"
export LD_LIBRARY_PATH="$root/lib/aarch64-linux-gnu${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

exec "$root/bin/osu_client" "$@"
